name: tuxclient
services:
  tuxclient:
    image: cooldockerizer93/tuxclient
    environment:
      - UID=1000  # Change as needed
      - GID=1000  # Change as needed
      - W_API_KEY=OpenWeatherMap_api_key # If you want weather station fallback for exterior temp and humidity, go on, if not, leave blank
      - BASE_URL=http://tuxedb.local/ # Put a real backend base url like http://192.168.1.30:6060/
      - TZ=Your_Timezone
      - SLEEP_DURATION=60 # Change as needed in seconds
      - LOCATION=City Name,Cuntry_Code # For example: Los Angeles,US
    volumes:
      - ./backup:/app/backup
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0" # Change as needed, must be the actual sensor device
    restart: unless-stopped
