name: tuxclient
services:
  tuxclient:
    image: cooldockerizer93/tuxclient
    environment:
      - UID=1000  # Change as needed
      - GID=1000  # Change as needed
      - W_API_KEY=OpenWeatherMap_api_key
      - BASE_URL=http://tuxedb.host/
      - TZ=Your_Timezone
    volumes:
      - ./backup:/app/backup
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0" # Change as needed
