name: tuxedb
services:
  tuxedb:
    image: cooldockerizer93/tuxedb
    environment:
      - UID=1000  # Change as needed
      - GID=1000  # Change as needed
    ports:
      - "6060:6060"
    volumes:
      - ./db:/app/instance
